# -*- coding: utf-8 -*-
# Generated by Django 1.9a1 on 2015-10-13 18:50
from __future__ import unicode_literals

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20150929_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=account.models.user_profile_picture),
        ),
    ]
