# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2015-10-21 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(blank=True, choices=[(b'male', b'Male'), (b'female', b'Female'), (b'other', b'Other')], max_length=10, null=True),
        ),
    ]
