# -*- coding: utf-8 -*-
# Generated by Django 1.9a1 on 2015-10-06 14:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20150806_0140'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2015, 10, 6, 14, 20, 18, 173592, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2015, 10, 6, 14, 20, 24, 868776, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
