# -*- coding: utf-8 -*-
# Generated by Django 1.9a1 on 2015-10-13 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_auto_20151013_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='is_anonymous',
            field=models.BooleanField(default=False, help_text=b'Valid for complete anonymous apps. Requires admin permission'),
        ),
    ]
