# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2015-10-22 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_resource', '0005_auto_20151022_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='degree',
            field=models.CharField(choices=[[b'BTECH', b'Bachelor of Technology'], [b'MTECH', b'Master of Technology'], [b'DD', b'Dual Degree'], [b'MSC', b'Master of Science'], [b'PHD', b'Doctor of Philosophy'], [b'MDES', b'Master of Design'], [b'MPHIL', b'Master of Philosophy'], [b'MMG', b'Master of Management']], max_length=6),
        ),
    ]
