# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2015-10-22 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_resource', '0006_auto_20151022_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='department',
            field=models.CharField(blank=True, choices=[[b'AE', b'Aerospace Engineering'], [b'BB', b'Biosciences and Bioengineering'], [b'CHE', b'Chemical Engineering'], [b'CH', b'Chemistry'], [b'CLE', b'Civil Engineering'], [b'CSE', b'Computer Science & Engineering'], [b'ES', b'Earth Sciences'], [b'EE', b'Electrical Engineering'], [b'ESE', b'Energy Science and Engineering'], [b'HSS', b'Humanities & Social Science'], [b'IDC', b'Industrial Design Centre'], [b'MM', b'Mathematics'], [b'ME', b'Mechanical Engineering'], [b'MEMS', b'Metallurgical Engineering & Materials Science'], [b'PH', b'Physics'], [b'ASC', b'Application Software Centre '], [b'CRNTS', b'Centre for Research in Nanotechnology and Science '], [b'CASDE', b'Centre for Aerospace Systems Design and Engineering '], [b'CC', b'Computer Centre '], [b'CDEEP', b'Centre for Distance Engineering Education Programme '], [b'CESE', b'Centre for Environmental Science and Engineering '], [b'CSRE', b'Centre of Studies in Resources Engineering '], [b'CTARA', b'Centre for Technology Alternatives for Rural Areas '], [b'CFDVS', b'Centre for Formal Design and Verification of Software '], [b'CUSE', b'Centre for Urban Science and Engineering '], [b'DSCE', b'Desai Sethi Centre for Entrepreneurship '], [b'IITBMRA', b'IITB-Monash Research Academy'], [b'NCAIR', b'National Centre for Aerospace Innovation and Research '], [b'NCM', b'National Centre for Mathematics '], [b'SAIF', b'Sophisticated Analytical Instrument Facility '], [b'TCTD', b'Tata Center for Technology and Design '], [b'WRCB', b'Wadhwani Research Centre for Bioengineering '], [b'SJMSOM', b'Shailesh J. Mehta School of Management'], [b'IDP:CLS', b'Climate Studies'], [b'IDP:ET', b'Educational Technology'], [b'IDP:IEOR', b'Industrial Engineering and Operations Research '], [b'IDP:SCE', b'Systems and Control Engineering']], max_length=8, null=True),
        ),
    ]
